# Generated by Django 5.1.2 on 2024-11-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
